### ISSUE TITLE
Possible packaging issue

### ISSUE THREAD

**Issue by vog** [zopefoundation/zope.deprecation#8]
It is currently impossible to install both `zope.interface` and `zope.deprecation` with `pip install --target`. This is probably a bug in `setuptools`, but maybe it is also a packaging issue with `zope.interface` and `zope.deprecation`?

For details, see: https://github.com/pypa/setuptools/issues/1071

**Comment by jamadden** [comment]
The use of namespace packages, setuptools, and setup.py is pretty much standard across all the zope distributions. I'm inclined to feel like this is a pip, setuptools, or possibly even wheel issue, especially since it was only produced with an unusual command on one particular system.

It seems to me we can probably close the issue here and continue tracking it with the setuptools issue that was opened. If there's further reason to believe there's something specific to just this package, feel free to reopen.
